### ISSUE TITLE
Vagrant Box Not Found?

### ISSUE THREAD

**Issue by budhajeewa** [antoniofrignani/laravel-homestead-settler-32#1]
Running `vagrant init antoniofrignani/laravel-homestead-settler-32` throws 404.

Following is the complete terminal dump:

``` bash
$ vagrant init antoniofrignani/laravel-homestead-settler-32
A `Vagrantfile` has been placed in this directory. ...

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'antoniofrignani/laravel-homestead-settler-32' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'antoniofrignani/laravel-homestead-settler-32'
    default: URL: https://atlas.hashicorp.com/antoniofrignani/laravel-homestead-settler-32
==> default: Adding box 'antoniofrignani/laravel-homestead-settler-32' (v0.1.1) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/antoniofrignani/boxes/laravel-homestead-settler-32/versions/0.1.1/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
```

Any idea why?

**Comment by Xplouder** [comment]
Apparently the website which "https://atlas.hashicorp.com/antoniofrignani/boxes/laravel-homestead-settler-32/versions/0.1.1/providers/virtualbox.box" redirect is offline.
Seems like the website is maintenance or something.

**Comment by budhajeewa** [comment]
@Xplouder : Yeah. Thanks for confirming.

@antoniofrignani : Can you please see into this?

**Comment by antoniofrignani** [comment]
Sorry guys, i had to put it down since someone redirected their own solutions (even further without giving credits back) to my image on the server. Unfortunately, bandwidth costs to me and, since i am not using it anymore, i just wiped it.

**Comment by Xplouder** [comment]
I just uploaded your compressed box in case anyone needs it. 
Download link: https://mega.nz/#!0gg0wT6A!66SNpRq6CYCojjKFr471GgXvyuyj6HS-DlgJ-5CC75A

@antoniofrignani Please let me know if if i'm allowed to distribute it.
